Add and remove accounts in the wallet
CityOfZion/neo-mamba pull request #89
Opened 2021-05-11 20:10 UTC by meevee98

implemented the methods to include and remove accounts

closes #63

2021-05-12 09:25 UTC, ixje requested changes
Can you also add doc strings?

2021-05-12 09:25 UTC, ixje commented on neo3/wallet/wallet.py
> +            raise ValueError("Label is already used by an account '{0}'", account.label)
Please use f-strings, which is used in the rest of mamba.

2021-05-12 09:25 UTC, ixje commented on neo3/wallet/wallet.py
> +    def _get_account_by_label(self, label: str) -> Optional[Account]:
I think this method would be useful if its public as `account_get_by_label`. We can later on add more `account_get_*` helpers

2021-05-13 08:09 UTC, ixje commented
Can you please solve the conflict? I've asked Ricardo if I can be added to the mamba repo at the simplitech org, because I can't add commits and move this forward due to this https://github.com/isaacs/github/issues/1681#issue-508922256

2021-05-13 14:05 UTC, meevee98 commented
Done

2021-05-13 17:26 UTC, ixje approved these changes
THanks! 🥇

2021-05-13 17:26 UTC, merged